version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /runPGRTK.wdl
    testParameterFiles:
      - /test.wdl.json
    authors:
      - orcid: 0000-0001-5739-861X
    name: PGRTK-cloud
    topic:  PGRTK-cloud


# version: 1.2
# workflows:
#   subclass: WDL
#   primaryDescriptorPath: /runPGRTK.wdl
#   testParameterFiles: 
#     - /test.wdl.json
#   readMePath: /README.md
#   authors:
#     name: Xinchang Zheng
#     email: zhengxc93@gmail.com


# version: 1.2

# tools:
#   - subclass: WDL
#     primaryDescriptorPath: /runPGRTK.wdl
#     testParameterFiles:
#         - /test.wdl.json
#     authors:
#         - name: xinchang zheng
#           email: zhengxc93@gmail.com
#     topic: PGRTK-on-terra